apiVersion: v1
kind: Service
metadata:
  name: brewskie-lb
spec:
  type: LoadBalancer
  selector:
    app: brewskie
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: "TCP"
