apiVersion: apps/v1
kind: Deployment
metadata:
  name: brewskie-deployment
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: brewskie
  template:
    metadata:
      labels:
        app: brewskie
    spec:
      containers:
        - name: brewskie
          image: oxycabhru/brewskie
          ports:
            - containerPort: 3000
