apiVersion: apps/v1
kind: Deployment
metadata:
  name: brewskie-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: brewskie
  template:
    metadata:
      labels:
        app: brewskie
    spec:
      containers:
        - name: brewskie
          image: oxycabhru/brewskie:latest
          ports:
            - containerPort: 3000
