apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: umami
spec:
  rules:
    - host: analytics.getbrewskie.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: umami
                port:
                  number: 3000
