apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
    - host: getbrewskie.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            service:
              name: brewskie-lb
              port: 80
    - host: analytics.getbrewskie.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: umami-np
                port:
                  number: 3000
