name: Deploy to GCP
run-name: ${{ github.actor }} created a new commit and it is now being deployed.
on: 
  push:
    branches:
      - production
env:
  IMAGE: "oxycabhru/brewskie:latest"
jobs:
  TERRAFORM:
    name: Setup the cloud environment
    runs-on: ubuntu-latest
    steps:
      - name: Use repo files
        uses: actions/checkout@v2
      - name: Generate cred.json
        uses: frdrwrt/write-to-file@v1.3
        with:
          filepath: deploy/tf/cred.json
          content: ${{ secrets.GCLOUD_PRIVATE_KEY }}
          mode: 744
      - uses: hashicorp/setup-terraform@v2.0.3
      - run: terraform init
        working-directory: deploy/tf
      - run: terraform apply -auto-approve
        working-directory: deploy/tf
      - name: Retrieve static ip from gcloud
        id: static_ip
        run: echo STATIC_IP=$(terraform output static_ip | tr -d '"') >> $GITHUB_OUTPUT
  BUILD:
    name: Build and publish a new Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE }}

  DEPLOY:
    name: Deploy a rolling update to GCP
    environment:
      name: getbrewskie.com
      url: http://getbrewskie.com
    needs:
      - BUILD
      - TERRAFORM
    runs-on: ubuntu-latest
    env:
      GKE_CLUSTER: "brewskie-cluster"
      GKE_REGION: "us-central1"
    steps:
      - name: Use repo files
        uses: actions/checkout@v2
      - name: Setup GCloud CLI
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCLOUD_PRIVATE_KEY }}
      - name: Retrieve cluster info for use with kubectl
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_REGION }}
      - name: Apply resources
        run: kubectl apply -f ./deploy/kube
      - name: Refresh image
        run: kubectl rollout restart deployment/brewskie-deployment